# This is a basic workflow to help you get started with Actions

name: issue comment 

on:
  issue_comment:
    types: [created]

   
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - uses: actions/github-script@v6
        if: always()
        with:
          script: |
             echo  "Remove label"
