name: Check Issue Label

on:
  issue_comment:
    types: [created]

jobs:
  check_label_job:
    runs-on: ubuntu-latest

    steps:
      - name: Remove label
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            github.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo, 
              issue_number: context.payload.issue.number,
              name: 'actions-importer-running'
            });
