name: Check Issue Label

on:
  issues:
    types: [created]

jobs:
  check_label_job:
    runs-on: ubuntu-latest

    steps:
      - name: Check if label exists
        id: check_label
        uses: actions/github-script@v6
        with:
          script: |
            const labels = context.payload.issue.labels.map(label => label.name);
            core.setOutput('labelExists', labels.includes('actions-importer-running'));

      - name: Remove label
        if: steps.check_label.outputs.labelExists == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            github.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo, 
              issue_number: context.payload.issue.number,
              name: 'actions-importer-running'
            });
